# .github/workflows/main.yml

name: Scheduled and On-Demand Data Refresh

on:
  schedule:
    # (你的定时规则保持不变)
    - cron: '30,45 1 * * 1-5'
    - cron: '0,15,30,45 2-6 * * 1-5'
    - cron: '0,15,30,45 7-8 * * 1-5'
    
  workflow_dispatch:
    # 增加一个输入参数，这样可以从API调用时传入
    inputs:
      trigger_source:
        description: 'Source of the trigger (e.g., "manual" or "api_call")'
        required: false
        default: 'manual_ui'

jobs:
  build-and-commit:
    name: Build Data and Commit to Repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ... (前面步骤不变)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 增加一步来打印触发源
      - name: Log trigger source
        run: echo "Workflow triggered by: ${{ github.event.inputs.trigger_source || github.event_name }}"

      - name: Run data fetching script
        run: python api/index.py

      # 提交并推送变动
      - name: Commit and push if changed
        # 使用 env 块来安全地创建环境变量，避免 shell 语法冲突
        env:
          COMMIT_MSG: "chore(data): Update market data (Trigger: ${{ github.event.inputs.trigger_source || github.event_name }})"
        run: |
          # 配置 git 用户信息
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加变动到暂存区
          git add data/
          
          # 检查是否有文件变动，并使用环境变量进行提交
          # "$COMMIT_MSG" 会被 shell 正确地替换为 env 块中定义的内容
          git diff --staged --quiet || (git commit -m "$COMMIT_MSG" && git push)
          
          echo "Data commit process finished."
